// Beat Drop session chart
/** Gap between successive notes' t_expected (center on hit line). */
export const BEAT_GAP_MS = Object.freeze({ 80: 750, 140: 429 })

/**
 * expected_hit_time_ms — time from note first appearing at top
 * until its center reaches the horizontal hit line.
 */
export const EXPECTED_HIT_TIME_MS = Object.freeze({ 80: 2200, 140: 1400 })

export const SESSION_DURATION_MS = 110800
export const DEVICE_LATENCY_MS = 35
export const LANE_CENTER = {
    1: { x: 100, y: 500 },
    2: { x: 200, y: 500 },
    3: { x: 300, y: 500 },
    4: { x: 400, y: 500 },
    5: { x: 500, y: 500 }
}
export const SPEED_POPUP_AT_MS = 22000 // after Block A ends, before Block B
export const CHORD_POPUP_AT_MS = 41800 // after Block B ends, before Block C
export const AVOID_POPUP_AT_MS = 59300 // after Block C ends, before Block D
export const FOLLOW_POPUP_AT_MS = 88800 // after Block D ends, before Block E
export const POPUP_AUTO_CLOSE_MS = 5000

/**
 * First chart event for each level A–E (by row order).
 */
export function getFirstNodePerLevel(chart = SESSION_CHART) {
    const firstByLevel = new Map()
    for (const e of chart) {
        if (!firstByLevel.has(e.block_id)) firstByLevel.set(e.block_id, e)
    }
    return firstByLevel
}

/**
 * Charted fall times (not screen-measured). Prefer live DOM probe in PlayArea.
 */
export function logFirstNodeFallTimesPerLevel(chart = SESSION_CHART) {
    const rows = [...getFirstNodePerLevel(chart).entries()].map(([level, e]) => ({
        level,
        row_num: e.row_num,
        event_type: e.event_type,
        lane_intended: e.lane_intended,
        t_spawn: e.t_spawn,
        t_expected: e.t_expected,
        charted_appear_to_center_ms: e.t_expected - e.t_spawn,
        expected_hit_time_ms: e.expected_hit_time_ms,
        tempo_bpm: e.tempo_bpm
    }))
    console.log("[BeatDrop] charted first-node fall times (per level)", rows)
    return rows
}

export const SESSION_CHART = [
    {
        row_num: 1,
        block_id: "A",
        trial_index: 1,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 0,
        t_expected: 2200,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 2,
        block_id: "A",
        trial_index: 2,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 3,
        hand_zone: "Center",
        t_spawn: 750,
        t_expected: 2950,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 300,
        y_center: 500
    },
    {
        row_num: 3,
        block_id: "A",
        trial_index: 3,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 5,
        hand_zone: "Right",
        t_spawn: 1500,
        t_expected: 3700,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 500,
        y_center: 500
    },
    {
        row_num: 4,
        block_id: "A",
        trial_index: 4,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 2250,
        t_expected: 4450,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 5,
        block_id: "A",
        trial_index: 5,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 4,
        hand_zone: "Right",
        t_spawn: 3000,
        t_expected: 5200,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 400,
        y_center: 500
    },
    {
        row_num: 6,
        block_id: "A",
        trial_index: 6,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 3750,
        t_expected: 5950,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 7,
        block_id: "A",
        trial_index: 7,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 3,
        hand_zone: "Center",
        t_spawn: 4500,
        t_expected: 6700,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 300,
        y_center: 500
    },
    {
        row_num: 8,
        block_id: "A",
        trial_index: 8,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 5250,
        t_expected: 7450,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 9,
        block_id: "A",
        trial_index: 9,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 5,
        hand_zone: "Right",
        t_spawn: 6000,
        t_expected: 8200,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 500,
        y_center: 500
    },
    {
        row_num: 10,
        block_id: "A",
        trial_index: 10,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 6750,
        t_expected: 8950,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 11,
        block_id: "A",
        trial_index: 11,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 4,
        hand_zone: "Right",
        t_spawn: 7500,
        t_expected: 9700,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 400,
        y_center: 500
    },
    {
        row_num: 12,
        block_id: "A",
        trial_index: 12,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 3,
        hand_zone: "Center",
        t_spawn: 8250,
        t_expected: 10450,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 300,
        y_center: 500
    },
    {
        row_num: 13,
        block_id: "A",
        trial_index: 13,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 9000,
        t_expected: 11200,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 14,
        block_id: "A",
        trial_index: 14,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 5,
        hand_zone: "Right",
        t_spawn: 9750,
        t_expected: 11950,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 500,
        y_center: 500
    },
    {
        row_num: 15,
        block_id: "A",
        trial_index: 15,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 10500,
        t_expected: 12700,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 16,
        block_id: "A",
        trial_index: 16,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 4,
        hand_zone: "Right",
        t_spawn: 11250,
        t_expected: 13450,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 400,
        y_center: 500
    },
    {
        row_num: 17,
        block_id: "A",
        trial_index: 17,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 12000,
        t_expected: 14200,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 18,
        block_id: "A",
        trial_index: 18,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 3,
        hand_zone: "Center",
        t_spawn: 12750,
        t_expected: 14950,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 300,
        y_center: 500
    },
    {
        row_num: 19,
        block_id: "A",
        trial_index: 19,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 5,
        hand_zone: "Right",
        t_spawn: 13500,
        t_expected: 15700,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 500,
        y_center: 500
    },
    {
        row_num: 20,
        block_id: "A",
        trial_index: 20,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 14250,
        t_expected: 16450,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 21,
        block_id: "A",
        trial_index: 21,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 15000,
        t_expected: 17200,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 22,
        block_id: "A",
        trial_index: 22,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 4,
        hand_zone: "Right",
        t_spawn: 15750,
        t_expected: 17950,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 400,
        y_center: 500
    },
    {
        row_num: 23,
        block_id: "A",
        trial_index: 23,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 3,
        hand_zone: "Center",
        t_spawn: 16500,
        t_expected: 18700,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 300,
        y_center: 500
    },
    {
        row_num: 24,
        block_id: "A",
        trial_index: 24,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 5,
        hand_zone: "Right",
        t_spawn: 17250,
        t_expected: 19450,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 500,
        y_center: 500
    },
    {
        row_num: 25,
        block_id: "A",
        trial_index: 25,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 18000,
        t_expected: 20200,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 26,
        block_id: "A",
        trial_index: 26,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 3,
        hand_zone: "Center",
        t_spawn: 18750,
        t_expected: 20950,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 300,
        y_center: 500
    },
    {
        row_num: 27,
        block_id: "B",
        trial_index: 1,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 22000,
        t_expected: 23400,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 28,
        block_id: "B",
        trial_index: 2,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 4,
        hand_zone: "Right",
        t_spawn: 22429,
        t_expected: 23829,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 400,
        y_center: 500
    },
    {
        row_num: 29,
        block_id: "B",
        trial_index: 3,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 22858,
        t_expected: 24258,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 30,
        block_id: "B",
        trial_index: 4,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 5,
        hand_zone: "Right",
        t_spawn: 23287,
        t_expected: 24687,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 500,
        y_center: 500
    },
    {
        row_num: 31,
        block_id: "B",
        trial_index: 5,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 3,
        hand_zone: "Center",
        t_spawn: 23716,
        t_expected: 25116,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 300,
        y_center: 500
    },
    {
        row_num: 32,
        block_id: "B",
        trial_index: 6,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 24145,
        t_expected: 25545,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 33,
        block_id: "B",
        trial_index: 7,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 4,
        hand_zone: "Right",
        t_spawn: 24574,
        t_expected: 25974,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 400,
        y_center: 500
    },
    {
        row_num: 34,
        block_id: "B",
        trial_index: 8,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 25003,
        t_expected: 26403,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 35,
        block_id: "B",
        trial_index: 9,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 5,
        hand_zone: "Right",
        t_spawn: 25432,
        t_expected: 26832,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 500,
        y_center: 500
    },
    {
        row_num: 36,
        block_id: "B",
        trial_index: 10,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 25861,
        t_expected: 27261,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 37,
        block_id: "B",
        trial_index: 11,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 3,
        hand_zone: "Center",
        t_spawn: 26290,
        t_expected: 27690,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 300,
        y_center: 500
    },
    {
        row_num: 38,
        block_id: "B",
        trial_index: 12,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 26719,
        t_expected: 28119,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 39,
        block_id: "B",
        trial_index: 13,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 4,
        hand_zone: "Right",
        t_spawn: 27148,
        t_expected: 28548,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 400,
        y_center: 500
    },
    {
        row_num: 40,
        block_id: "B",
        trial_index: 14,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 5,
        hand_zone: "Right",
        t_spawn: 27577,
        t_expected: 28977,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 500,
        y_center: 500
    },
    {
        row_num: 41,
        block_id: "B",
        trial_index: 15,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 28006,
        t_expected: 29406,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 42,
        block_id: "B",
        trial_index: 16,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 28435,
        t_expected: 29835,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 43,
        block_id: "B",
        trial_index: 17,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 3,
        hand_zone: "Center",
        t_spawn: 28864,
        t_expected: 30264,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 300,
        y_center: 500
    },
    {
        row_num: 44,
        block_id: "B",
        trial_index: 18,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 5,
        hand_zone: "Right",
        t_spawn: 29293,
        t_expected: 30693,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 500,
        y_center: 500
    },
    {
        row_num: 45,
        block_id: "B",
        trial_index: 19,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 4,
        hand_zone: "Right",
        t_spawn: 29722,
        t_expected: 31122,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 400,
        y_center: 500
    },
    {
        row_num: 46,
        block_id: "B",
        trial_index: 20,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 30151,
        t_expected: 31551,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 47,
        block_id: "B",
        trial_index: 21,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 30580,
        t_expected: 31980,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 48,
        block_id: "B",
        trial_index: 22,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 3,
        hand_zone: "Center",
        t_spawn: 31009,
        t_expected: 32409,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 300,
        y_center: 500
    },
    {
        row_num: 49,
        block_id: "B",
        trial_index: 23,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 5,
        hand_zone: "Right",
        t_spawn: 31438,
        t_expected: 32838,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 500,
        y_center: 500
    },
    {
        row_num: 50,
        block_id: "B",
        trial_index: 24,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 4,
        hand_zone: "Right",
        t_spawn: 31867,
        t_expected: 33267,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 400,
        y_center: 500
    },
    {
        row_num: 51,
        block_id: "B",
        trial_index: 25,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 32296,
        t_expected: 33696,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 52,
        block_id: "B",
        trial_index: 26,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 32725,
        t_expected: 34125,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 53,
        block_id: "B",
        trial_index: 27,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 3,
        hand_zone: "Center",
        t_spawn: 33154,
        t_expected: 34554,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 300,
        y_center: 500
    },
    {
        row_num: 54,
        block_id: "B",
        trial_index: 28,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 4,
        hand_zone: "Right",
        t_spawn: 33583,
        t_expected: 34983,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 400,
        y_center: 500
    },
    {
        row_num: 55,
        block_id: "B",
        trial_index: 29,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 5,
        hand_zone: "Right",
        t_spawn: 34012,
        t_expected: 35412,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 500,
        y_center: 500
    },
    {
        row_num: 56,
        block_id: "B",
        trial_index: 30,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 34441,
        t_expected: 35841,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 57,
        block_id: "B",
        trial_index: 31,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 34870,
        t_expected: 36270,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 58,
        block_id: "B",
        trial_index: 32,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 3,
        hand_zone: "Center",
        t_spawn: 35299,
        t_expected: 36699,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 300,
        y_center: 500
    },
    {
        row_num: 59,
        block_id: "B",
        trial_index: 33,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 4,
        hand_zone: "Right",
        t_spawn: 35728,
        t_expected: 37128,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 400,
        y_center: 500
    },
    {
        row_num: 60,
        block_id: "B",
        trial_index: 34,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 5,
        hand_zone: "Right",
        t_spawn: 36157,
        t_expected: 37557,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 500,
        y_center: 500
    },
    {
        row_num: 61,
        block_id: "B",
        trial_index: 35,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 36586,
        t_expected: 37986,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 62,
        block_id: "B",
        trial_index: 36,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 37015,
        t_expected: 38415,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 63,
        block_id: "B",
        trial_index: 37,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 3,
        hand_zone: "Center",
        t_spawn: 37444,
        t_expected: 38844,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 300,
        y_center: 500
    },
    {
        row_num: 64,
        block_id: "B",
        trial_index: 38,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 4,
        hand_zone: "Right",
        t_spawn: 37873,
        t_expected: 39273,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 400,
        y_center: 500
    },
    {
        row_num: 65,
        block_id: "B",
        trial_index: 39,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 5,
        hand_zone: "Right",
        t_spawn: 38302,
        t_expected: 39702,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 500,
        y_center: 500
    },
    {
        row_num: 66,
        block_id: "B",
        trial_index: 40,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 38731,
        t_expected: 40131,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 67,
        block_id: "B",
        trial_index: 41,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 39160,
        t_expected: 40560,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 68,
        block_id: "B",
        trial_index: 42,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 3,
        hand_zone: "Center",
        t_spawn: 39589,
        t_expected: 40989,
        expected_hit_time_ms: 1400,
        tempo_bpm: 140,
        x_center: 300,
        y_center: 500
    },
    {
        row_num: 69,
        block_id: "C",
        trial_index: 1,
        event_type: "chord_L",
        similarity_level: null,
        chord_pair_id: "C1",
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 41800,
        t_expected: 44000,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 70,
        block_id: "C",
        trial_index: 1,
        event_type: "chord_R",
        similarity_level: null,
        chord_pair_id: "C1",
        lane_intended: 5,
        hand_zone: "Right",
        t_spawn: 41800,
        t_expected: 44000,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 500,
        y_center: 500
    },
    {
        row_num: 71,
        block_id: "C",
        trial_index: 2,
        event_type: "chord_L",
        similarity_level: null,
        chord_pair_id: "C2",
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 42550,
        t_expected: 44750,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 72,
        block_id: "C",
        trial_index: 2,
        event_type: "chord_R",
        similarity_level: null,
        chord_pair_id: "C2",
        lane_intended: 4,
        hand_zone: "Right",
        t_spawn: 42550,
        t_expected: 44750,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 400,
        y_center: 500
    },
    {
        row_num: 73,
        block_id: "C",
        trial_index: 3,
        event_type: "chord_L",
        similarity_level: null,
        chord_pair_id: "C3",
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 43300,
        t_expected: 45500,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 74,
        block_id: "C",
        trial_index: 3,
        event_type: "chord_R",
        similarity_level: null,
        chord_pair_id: "C3",
        lane_intended: 4,
        hand_zone: "Right",
        t_spawn: 43300,
        t_expected: 45500,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 400,
        y_center: 500
    },
    {
        row_num: 75,
        block_id: "C",
        trial_index: 4,
        event_type: "chord_L",
        similarity_level: null,
        chord_pair_id: "C4",
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 44050,
        t_expected: 46250,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 76,
        block_id: "C",
        trial_index: 4,
        event_type: "chord_R",
        similarity_level: null,
        chord_pair_id: "C4",
        lane_intended: 5,
        hand_zone: "Right",
        t_spawn: 44050,
        t_expected: 46250,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 500,
        y_center: 500
    },
    {
        row_num: 77,
        block_id: "C",
        trial_index: 5,
        event_type: "chord_L",
        similarity_level: null,
        chord_pair_id: "C5",
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 44800,
        t_expected: 47000,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 78,
        block_id: "C",
        trial_index: 5,
        event_type: "chord_R",
        similarity_level: null,
        chord_pair_id: "C5",
        lane_intended: 5,
        hand_zone: "Right",
        t_spawn: 44800,
        t_expected: 47000,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 500,
        y_center: 500
    },
    {
        row_num: 79,
        block_id: "C",
        trial_index: 6,
        event_type: "chord_L",
        similarity_level: null,
        chord_pair_id: "C6",
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 45550,
        t_expected: 47750,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 80,
        block_id: "C",
        trial_index: 6,
        event_type: "chord_R",
        similarity_level: null,
        chord_pair_id: "C6",
        lane_intended: 4,
        hand_zone: "Right",
        t_spawn: 45550,
        t_expected: 47750,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 400,
        y_center: 500
    },
    {
        row_num: 81,
        block_id: "C",
        trial_index: 7,
        event_type: "chord_L",
        similarity_level: null,
        chord_pair_id: "C7",
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 46300,
        t_expected: 48500,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 82,
        block_id: "C",
        trial_index: 7,
        event_type: "chord_R",
        similarity_level: null,
        chord_pair_id: "C7",
        lane_intended: 4,
        hand_zone: "Right",
        t_spawn: 46300,
        t_expected: 48500,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 400,
        y_center: 500
    },
    {
        row_num: 83,
        block_id: "C",
        trial_index: 8,
        event_type: "chord_L",
        similarity_level: null,
        chord_pair_id: "C8",
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 47050,
        t_expected: 49250,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 84,
        block_id: "C",
        trial_index: 8,
        event_type: "chord_R",
        similarity_level: null,
        chord_pair_id: "C8",
        lane_intended: 5,
        hand_zone: "Right",
        t_spawn: 47050,
        t_expected: 49250,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 500,
        y_center: 500
    },
    {
        row_num: 85,
        block_id: "C",
        trial_index: 9,
        event_type: "chord_L",
        similarity_level: null,
        chord_pair_id: "C9",
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 47800,
        t_expected: 50000,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 86,
        block_id: "C",
        trial_index: 9,
        event_type: "chord_R",
        similarity_level: null,
        chord_pair_id: "C9",
        lane_intended: 5,
        hand_zone: "Right",
        t_spawn: 47800,
        t_expected: 50000,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 500,
        y_center: 500
    },
    {
        row_num: 87,
        block_id: "C",
        trial_index: 10,
        event_type: "chord_L",
        similarity_level: null,
        chord_pair_id: "C10",
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 48550,
        t_expected: 50750,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 88,
        block_id: "C",
        trial_index: 10,
        event_type: "chord_R",
        similarity_level: null,
        chord_pair_id: "C10",
        lane_intended: 4,
        hand_zone: "Right",
        t_spawn: 48550,
        t_expected: 50750,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 400,
        y_center: 500
    },
    {
        row_num: 89,
        block_id: "C",
        trial_index: 11,
        event_type: "chord_L",
        similarity_level: null,
        chord_pair_id: "C11",
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 49300,
        t_expected: 51500,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 90,
        block_id: "C",
        trial_index: 11,
        event_type: "chord_R",
        similarity_level: null,
        chord_pair_id: "C11",
        lane_intended: 4,
        hand_zone: "Right",
        t_spawn: 49300,
        t_expected: 51500,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 400,
        y_center: 500
    },
    {
        row_num: 91,
        block_id: "C",
        trial_index: 12,
        event_type: "chord_L",
        similarity_level: null,
        chord_pair_id: "C12",
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 50050,
        t_expected: 52250,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 92,
        block_id: "C",
        trial_index: 12,
        event_type: "chord_R",
        similarity_level: null,
        chord_pair_id: "C12",
        lane_intended: 5,
        hand_zone: "Right",
        t_spawn: 50050,
        t_expected: 52250,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 500,
        y_center: 500
    },
    {
        row_num: 93,
        block_id: "C",
        trial_index: 13,
        event_type: "chord_L",
        similarity_level: null,
        chord_pair_id: "C13",
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 50800,
        t_expected: 53000,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 94,
        block_id: "C",
        trial_index: 13,
        event_type: "chord_R",
        similarity_level: null,
        chord_pair_id: "C13",
        lane_intended: 5,
        hand_zone: "Right",
        t_spawn: 50800,
        t_expected: 53000,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 500,
        y_center: 500
    },
    {
        row_num: 95,
        block_id: "C",
        trial_index: 14,
        event_type: "chord_L",
        similarity_level: null,
        chord_pair_id: "C14",
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 51550,
        t_expected: 53750,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 96,
        block_id: "C",
        trial_index: 14,
        event_type: "chord_R",
        similarity_level: null,
        chord_pair_id: "C14",
        lane_intended: 4,
        hand_zone: "Right",
        t_spawn: 51550,
        t_expected: 53750,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 400,
        y_center: 500
    },
    {
        row_num: 97,
        block_id: "C",
        trial_index: 15,
        event_type: "chord_L",
        similarity_level: null,
        chord_pair_id: "C15",
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 52300,
        t_expected: 54500,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 98,
        block_id: "C",
        trial_index: 15,
        event_type: "chord_R",
        similarity_level: null,
        chord_pair_id: "C15",
        lane_intended: 4,
        hand_zone: "Right",
        t_spawn: 52300,
        t_expected: 54500,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 400,
        y_center: 500
    },
    {
        row_num: 99,
        block_id: "C",
        trial_index: 16,
        event_type: "chord_L",
        similarity_level: null,
        chord_pair_id: "C16",
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 53050,
        t_expected: 55250,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 100,
        block_id: "C",
        trial_index: 16,
        event_type: "chord_R",
        similarity_level: null,
        chord_pair_id: "C16",
        lane_intended: 5,
        hand_zone: "Right",
        t_spawn: 53050,
        t_expected: 55250,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 500,
        y_center: 500
    },
    {
        row_num: 101,
        block_id: "C",
        trial_index: 17,
        event_type: "chord_L",
        similarity_level: null,
        chord_pair_id: "C17",
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 53800,
        t_expected: 56000,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 102,
        block_id: "C",
        trial_index: 17,
        event_type: "chord_R",
        similarity_level: null,
        chord_pair_id: "C17",
        lane_intended: 5,
        hand_zone: "Right",
        t_spawn: 53800,
        t_expected: 56000,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 500,
        y_center: 500
    },
    {
        row_num: 103,
        block_id: "C",
        trial_index: 18,
        event_type: "chord_L",
        similarity_level: null,
        chord_pair_id: "C18",
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 54550,
        t_expected: 56750,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 104,
        block_id: "C",
        trial_index: 18,
        event_type: "chord_R",
        similarity_level: null,
        chord_pair_id: "C18",
        lane_intended: 4,
        hand_zone: "Right",
        t_spawn: 54550,
        t_expected: 56750,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 400,
        y_center: 500
    },
    {
        row_num: 105,
        block_id: "C",
        trial_index: 19,
        event_type: "chord_L",
        similarity_level: null,
        chord_pair_id: "C19",
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 55300,
        t_expected: 57500,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 106,
        block_id: "C",
        trial_index: 19,
        event_type: "chord_R",
        similarity_level: null,
        chord_pair_id: "C19",
        lane_intended: 4,
        hand_zone: "Right",
        t_spawn: 55300,
        t_expected: 57500,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 400,
        y_center: 500
    },
    {
        row_num: 107,
        block_id: "C",
        trial_index: 20,
        event_type: "chord_L",
        similarity_level: null,
        chord_pair_id: "C20",
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 56050,
        t_expected: 58250,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 108,
        block_id: "C",
        trial_index: 20,
        event_type: "chord_R",
        similarity_level: null,
        chord_pair_id: "C20",
        lane_intended: 5,
        hand_zone: "Right",
        t_spawn: 56050,
        t_expected: 58250,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 500,
        y_center: 500
    },
    {
        row_num: 109,
        block_id: "D",
        trial_index: 1,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 59300,
        t_expected: 61500,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 110,
        block_id: "D",
        trial_index: 2,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 3,
        hand_zone: "Center",
        t_spawn: 60050,
        t_expected: 62250,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 300,
        y_center: 500
    },
    {
        row_num: 111,
        block_id: "D",
        trial_index: 3,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 60800,
        t_expected: 63000,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 112,
        block_id: "D",
        trial_index: 4,
        event_type: "decoy_note",
        similarity_level: 1,
        chord_pair_id: null,
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 61550,
        t_expected: 63750,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 113,
        block_id: "D",
        trial_index: 5,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 4,
        hand_zone: "Right",
        t_spawn: 62300,
        t_expected: 64500,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 400,
        y_center: 500
    },
    {
        row_num: 114,
        block_id: "D",
        trial_index: 6,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 5,
        hand_zone: "Right",
        t_spawn: 63050,
        t_expected: 65250,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 500,
        y_center: 500
    },
    {
        row_num: 115,
        block_id: "D",
        trial_index: 7,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 63800,
        t_expected: 66000,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 116,
        block_id: "D",
        trial_index: 8,
        event_type: "decoy_note",
        similarity_level: 2,
        chord_pair_id: null,
        lane_intended: 4,
        hand_zone: "Right",
        t_spawn: 64550,
        t_expected: 66750,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 400,
        y_center: 500
    },
    {
        row_num: 117,
        block_id: "D",
        trial_index: 9,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 3,
        hand_zone: "Center",
        t_spawn: 65300,
        t_expected: 67500,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 300,
        y_center: 500
    },
    {
        row_num: 118,
        block_id: "D",
        trial_index: 10,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 66050,
        t_expected: 68250,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 119,
        block_id: "D",
        trial_index: 11,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 4,
        hand_zone: "Right",
        t_spawn: 66800,
        t_expected: 69000,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 400,
        y_center: 500
    },
    {
        row_num: 120,
        block_id: "D",
        trial_index: 12,
        event_type: "decoy_note",
        similarity_level: 3,
        chord_pair_id: null,
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 67550,
        t_expected: 69750,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 121,
        block_id: "D",
        trial_index: 13,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 68300,
        t_expected: 70500,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 122,
        block_id: "D",
        trial_index: 14,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 5,
        hand_zone: "Right",
        t_spawn: 69050,
        t_expected: 71250,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 500,
        y_center: 500
    },
    {
        row_num: 123,
        block_id: "D",
        trial_index: 15,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 69800,
        t_expected: 72000,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 124,
        block_id: "D",
        trial_index: 16,
        event_type: "decoy_note",
        similarity_level: 1,
        chord_pair_id: null,
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 70550,
        t_expected: 72750,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 125,
        block_id: "D",
        trial_index: 17,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 3,
        hand_zone: "Center",
        t_spawn: 71300,
        t_expected: 73500,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 300,
        y_center: 500
    },
    {
        row_num: 126,
        block_id: "D",
        trial_index: 18,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 4,
        hand_zone: "Right",
        t_spawn: 72050,
        t_expected: 74250,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 400,
        y_center: 500
    },
    {
        row_num: 127,
        block_id: "D",
        trial_index: 19,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 72800,
        t_expected: 75000,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 128,
        block_id: "D",
        trial_index: 20,
        event_type: "decoy_note",
        similarity_level: 2,
        chord_pair_id: null,
        lane_intended: 5,
        hand_zone: "Right",
        t_spawn: 73550,
        t_expected: 75750,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 500,
        y_center: 500
    },
    {
        row_num: 129,
        block_id: "D",
        trial_index: 21,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 5,
        hand_zone: "Right",
        t_spawn: 74300,
        t_expected: 76500,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 500,
        y_center: 500
    },
    {
        row_num: 130,
        block_id: "D",
        trial_index: 22,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 75050,
        t_expected: 77250,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 131,
        block_id: "D",
        trial_index: 23,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 3,
        hand_zone: "Center",
        t_spawn: 75800,
        t_expected: 78000,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 300,
        y_center: 500
    },
    {
        row_num: 132,
        block_id: "D",
        trial_index: 24,
        event_type: "decoy_note",
        similarity_level: 3,
        chord_pair_id: null,
        lane_intended: 3,
        hand_zone: "Center",
        t_spawn: 76550,
        t_expected: 78750,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 300,
        y_center: 500
    },
    {
        row_num: 133,
        block_id: "D",
        trial_index: 25,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 4,
        hand_zone: "Right",
        t_spawn: 77300,
        t_expected: 79500,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 400,
        y_center: 500
    },
    {
        row_num: 134,
        block_id: "D",
        trial_index: 26,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 78050,
        t_expected: 80250,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 135,
        block_id: "D",
        trial_index: 27,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 5,
        hand_zone: "Right",
        t_spawn: 78800,
        t_expected: 81000,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 500,
        y_center: 500
    },
    {
        row_num: 136,
        block_id: "D",
        trial_index: 28,
        event_type: "decoy_note",
        similarity_level: 1,
        chord_pair_id: null,
        lane_intended: 4,
        hand_zone: "Right",
        t_spawn: 79550,
        t_expected: 81750,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 400,
        y_center: 500
    },
    {
        row_num: 137,
        block_id: "D",
        trial_index: 29,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 80300,
        t_expected: 82500,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 138,
        block_id: "D",
        trial_index: 30,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 3,
        hand_zone: "Center",
        t_spawn: 81050,
        t_expected: 83250,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 300,
        y_center: 500
    },
    {
        row_num: 139,
        block_id: "D",
        trial_index: 31,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 4,
        hand_zone: "Right",
        t_spawn: 81800,
        t_expected: 84000,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 400,
        y_center: 500
    },
    {
        row_num: 140,
        block_id: "D",
        trial_index: 32,
        event_type: "decoy_note",
        similarity_level: 2,
        chord_pair_id: null,
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 82550,
        t_expected: 84750,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 141,
        block_id: "D",
        trial_index: 33,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 83300,
        t_expected: 85500,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 142,
        block_id: "D",
        trial_index: 34,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 5,
        hand_zone: "Right",
        t_spawn: 84050,
        t_expected: 86250,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 500,
        y_center: 500
    },
    {
        row_num: 143,
        block_id: "D",
        trial_index: 35,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 84800,
        t_expected: 87000,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 144,
        block_id: "D",
        trial_index: 36,
        event_type: "decoy_note",
        similarity_level: 3,
        chord_pair_id: null,
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 85550,
        t_expected: 87750,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 145,
        block_id: "E",
        trial_index: 1,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 88800,
        t_expected: 91000,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 146,
        block_id: "E",
        trial_index: 2,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 3,
        hand_zone: "Center",
        t_spawn: 89550,
        t_expected: 91750,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 300,
        y_center: 500
    },
    {
        row_num: 147,
        block_id: "E",
        trial_index: 3,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 5,
        hand_zone: "Right",
        t_spawn: 90300,
        t_expected: 92500,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 500,
        y_center: 500
    },
    {
        row_num: 148,
        block_id: "E",
        trial_index: 4,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 91050,
        t_expected: 93250,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 149,
        block_id: "E",
        trial_index: 5,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 4,
        hand_zone: "Right",
        t_spawn: 91800,
        t_expected: 94000,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 400,
        y_center: 500
    },
    {
        row_num: 150,
        block_id: "E",
        trial_index: 6,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 92550,
        t_expected: 94750,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 151,
        block_id: "E",
        trial_index: 7,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 3,
        hand_zone: "Center",
        t_spawn: 93300,
        t_expected: 95500,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 300,
        y_center: 500
    },
    {
        row_num: 152,
        block_id: "E",
        trial_index: 8,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 94050,
        t_expected: 96250,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 153,
        block_id: "E",
        trial_index: 9,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 5,
        hand_zone: "Right",
        t_spawn: 94800,
        t_expected: 97000,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 500,
        y_center: 500
    },
    {
        row_num: 154,
        block_id: "E",
        trial_index: 10,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 95550,
        t_expected: 97750,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 155,
        block_id: "E",
        trial_index: 11,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 4,
        hand_zone: "Right",
        t_spawn: 96300,
        t_expected: 98500,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 400,
        y_center: 500
    },
    {
        row_num: 156,
        block_id: "E",
        trial_index: 12,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 3,
        hand_zone: "Center",
        t_spawn: 97050,
        t_expected: 99250,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 300,
        y_center: 500
    },
    {
        row_num: 157,
        block_id: "E",
        trial_index: 13,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 97800,
        t_expected: 100000,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 158,
        block_id: "E",
        trial_index: 14,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 5,
        hand_zone: "Right",
        t_spawn: 98550,
        t_expected: 100750,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 500,
        y_center: 500
    },
    {
        row_num: 159,
        block_id: "E",
        trial_index: 15,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 99300,
        t_expected: 101500,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 160,
        block_id: "E",
        trial_index: 16,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 4,
        hand_zone: "Right",
        t_spawn: 100050,
        t_expected: 102250,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 400,
        y_center: 500
    },
    {
        row_num: 161,
        block_id: "E",
        trial_index: 17,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 100800,
        t_expected: 103000,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 162,
        block_id: "E",
        trial_index: 18,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 3,
        hand_zone: "Center",
        t_spawn: 101550,
        t_expected: 103750,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 300,
        y_center: 500
    },
    {
        row_num: 163,
        block_id: "E",
        trial_index: 19,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 5,
        hand_zone: "Right",
        t_spawn: 102300,
        t_expected: 104500,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 500,
        y_center: 500
    },
    {
        row_num: 164,
        block_id: "E",
        trial_index: 20,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 103050,
        t_expected: 105250,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 165,
        block_id: "E",
        trial_index: 21,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 2,
        hand_zone: "Left",
        t_spawn: 103800,
        t_expected: 106000,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 200,
        y_center: 500
    },
    {
        row_num: 166,
        block_id: "E",
        trial_index: 22,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 4,
        hand_zone: "Right",
        t_spawn: 104550,
        t_expected: 106750,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 400,
        y_center: 500
    },
    {
        row_num: 167,
        block_id: "E",
        trial_index: 23,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 3,
        hand_zone: "Center",
        t_spawn: 105300,
        t_expected: 107500,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 300,
        y_center: 500
    },
    {
        row_num: 168,
        block_id: "E",
        trial_index: 24,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 5,
        hand_zone: "Right",
        t_spawn: 106050,
        t_expected: 108250,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 500,
        y_center: 500
    },
    {
        row_num: 169,
        block_id: "E",
        trial_index: 25,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 1,
        hand_zone: "Left",
        t_spawn: 106800,
        t_expected: 109000,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 100,
        y_center: 500
    },
    {
        row_num: 170,
        block_id: "E",
        trial_index: 26,
        event_type: "target_note",
        similarity_level: null,
        chord_pair_id: null,
        lane_intended: 3,
        hand_zone: "Center",
        t_spawn: 107550,
        t_expected: 109750,
        expected_hit_time_ms: 2200,
        tempo_bpm: 80,
        x_center: 300,
        y_center: 500
    }
]
